version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - DB_CONNECTION: mysql
          - DB_DATABASE: test1
          - DB_USERNAME: root
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: test1
    steps:
      - checkout
      - run: sudo apt-get update
      - run:
        command: |
          sudo apt-get install -y zlib1g-dev mariadb-client \
          wget git unzip libpq-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev
      - run: sudo docker-php-ext-install zip pdo_mysql
      - run: sudo docker-php-ext-configure gd --with-freetype-dir --with-jpeg-dir --with-png-dir
      - run: sudo docker-php-ext-install -j$(nproc) gd
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
          - node_modules
      - run: npm run dev
      - run: php artisan migrate
      - run: composer test